### ISSUE TITLE
Code review procedure undefined

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#110]
The code review procedure in step no. 2 of the [Review section](https://github.com/doubleunion/doubleunion#reviewing) of the readme is:

> Code review the Pull Request, commenting on any potential issues, improvements, or telling the person how awesome their code is.

It's possible that a more specific review procedure would be useful.

**Comment by brittag** [comment]
For context, this section is now at https://github.com/doubleunion/arooo#reviewing

I feel like it'd be nice to improve this section, but most of the maintainership / code review / app discussion happens between members in the #du-app channel or in person, so we probably don't need to document this bit extensively (we're already taking care of it).

I did just make a PR to note the channel in the readme, since it's part of our app development process for DU members. :)
