### ISSUE TITLE
Add a way to indicate which members are board members on members list 

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#200]
Our organization has a bunch of board members and many members, and it could be helpful for everyone's memory to visually indicate which people are board members on the general members list in the app (at /members/users), since that list is used for quick reference by members.

This would probably be a status that membership coordinators could manage on /admin/members, causing a superficial change to /members/users that says "board member" under "status" for the appropriate people.

**Comment by lilliealbert** [comment]
I feel like the board is a small enough % of the general membership that adding another user state for it is not great; what if we just listed who was on the board somewhere in the app?

I realize I'm advocating for hard-coding text instead of a dynamic solution, which is kind of ridiculous, but I'm just not sure there's an actual need for a dynamic solution, unless board turnover was so fast that we needed button to turn on and off board membership.

**Comment by lilliealbert** [comment]
Hey Britta, do you think having the board on the external website is good enough for this idea?

**Comment by brittag** [comment]
I think that's probably good enough for now, thanks!
