### ISSUE TITLE
Have an application/profile field for pronouns?

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#209]
Some DU members use they/their or other non-she/her pronouns, and it could be cool for members to have a place to indicate their pronouns in their applications/profiles so that other members know how to refer to them correctly, much like we have nametags at DU with space for pronouns. :)

This could be a field on the application, perhaps with a brief label noting that this doesn't affect their application, we just want to respect what they use. Then if they get accepted, this can become part of their profile displayed internally for other members (like Twitter links and so on).

**Comment by brittag** [comment]
Closed with a recent PR! Thanks @arbonap and @mathildemouw!

**Comment by mathildemouw** [comment]
I reverted the PR that added this feature because it turned out it wasn't quite done! @arbonap for some reason the pronoun wasn't saving from the application edit page, and we forgot we should add it to the user profile page so that members can see it once the person is accepted! We can pair on it and finish it up together later 😄

**Comment by arbonap** [comment]
Okay! On my local machine, I think I've successfully added the pronoun
field to the user profile page so that members can see it once the person
has been accepted.

Hmm, @mathildemouw <https://github.com/mathildemouw> any ideas as to why
the pronoun wasn't saving from the application edit page? I'll poke around
more.

Patricia A. Arbona
Software Developer
[image: GitHub-Mark-32px.png]arbonap <https://www.github.com/arbonap>[image:
noun_218720_cc.png](614)329-8370 arbonap
<https://www.linkedin.com/in/parbona>

**Comment by brittag** [comment]
This is added in https://github.com/doubleunion/arooo/pull/249 - hooray! Thanks all.
