### ISSUE TITLE
Interested in Arooo for a hackerspace in Chicago - what changes would you like us to make?

### ISSUE THREAD

**Issue by cswingler** [doubleunion/arooo#233]
Hello Double Union!

I'm Chris Swingler, the CTO at South Side Hackerspace Chicago (https://sshchicago.org). We've been demoing Arooo as a possibility for a membership management platform (after being less than impressed with solutions like Silkstart and Zoho) and so far it looks like this actually comes really close to actually meeting our needs as a hackerspace.

Are there any particular coding standards you'd like us to follow if we submit PRs, and what would be the best way to go about revising the copy for our needs?

Thanks!

**Comment by lilliealbert** [comment]
Hi Chris! Sorry for the slow reply, I've been chewing on what the best way to handle this was.

In a world where I could work on this app full-time, I'd want to turn it into a configurable masterpiece, where a hackerspace could fill in a few fields and pick a few colors and have an app for managing membership. I think in order to get there, we'd need to:

1. Start with moving all the Double Union specific strings into i18n YML files and make which "language" you are using for your deployment of the app configurable
1. Make all the email language configurable somehow (or just move it into YML, too)
1. Rewrite the application form so that it could be configured by the individual hackerspace
1. Bonus: make the main app colors configurable (although who doesn't love magenta 😄 )

...and probably a lot of other things that aren't coming to mind right now. Like, assets, maybe? But it's item no. 3 on that list is where I really start shaking in my boots, since reimplementing survey monkey well isn't something I have the time for or would want to ask of someone else just because they wanted to use the app. 

So! Instead of trying to do that right now, I'd suggest you make two forks of the app:
* one that's isn't downstream of the DU app on GitHub, that you actually deploy and use
* one official one (by GitHub's standards) where the DU app is upstream, in case you have any changes that you want to make PR's with

And if you don't find things you want to push back up to us, or if the SSH Chicago app diverges too far to make PRs with, that's totally cool with me. (One really silly reason for the non-downstream version as the real one is that then you get GitHub green boxes for commits, whereas you don't get those for commits on a fork unless they get merged into master.)

(The things about the application that would get pretty annoying to develop with, I think, are columns like [Application#agreement_female](https://github.com/doubleunion/arooo/blob/master/db/schema.rb#L24) and [Profile#feminism](https://github.com/doubleunion/arooo/blob/master/db/schema.rb#L77), where you could change the display text to be in a YML file quite easily, but then you have to remember that for your hackerspace, that actually maps to a totally different question.)

As for coding standards, mostly: write tests, and run them often!

**Comment by brittag** [comment]
I'm going to close this up for tidiness in our issues list, since this is a discussion from a few months ago, but please let us know if you have more questions about reusing Arooo! We're still excited for other people to reuse this. :)
