### ISSUE TITLE
Aws::SES::Errors::InvalidParameterValue: raised when new application submitted

### ISSUE THREAD

**Issue by mathildemouw** [doubleunion/arooo#243]
When a new application is submitted, this error is raised when the app tries to send the new application submitted email to members: `Aws::SES::Errors::InvalidParameterValue: Recipient count exceeds 50.` This is because [AWS does not a currently allow more than 50 recipients for an email](https://forums.aws.amazon.com/thread.jspa?threadID=97111).

One solution to this would be to send the new application email to the members list instead of every member individually.

**Comment by lilliealbert** [comment]
that sounds pretty great. one thing I talked to the board about was potentially limiting the email to just the link to it, because having a record of every application in every member's inbox isn't great from a security/confidentiality perspective. but that's a different issue >_<

For this, I think my only concern is that we should maintain filterability, but I think that's totally doable if we're keeping the subject line consistent. 😺

**Comment by compwron** [comment]
This error no longer occurs. 
```
member_emails = User.all_members.pluck(:email).compact
      (member_emails << JOIN_EMAIL).each do |email|
        ApplicationsMailer.notify_member_of_application(application, email).deliver_now
      end
```
