### ISSUE TITLE
Show more informative error message when a member double-sponsors

### ISSUE THREAD

**Issue by mathildemouw** [doubleunion/arooo#252]
We flash a `Sorry, something went wrong!` message when a member has already sponsored an application and tried to hit the button again. This confused someone so we might want a more informative message. 

We also may want the else case when a sponsorship cannot be saved to throw an error, so we can investigate what went wrong.

**Comment by compwron** [comment]
Unfortunately I think that this is not just a text change because the new text will need to know about what the failure was.

**Comment by brittag** [comment]
We can improve this text to say something like "Sorry, something went wrong! Sometimes this happens if you've already sponsored an application and try to sponsor it again. Try refreshing the page, checking the sponsorship status, and trying again to sponsor if you need to." Not perfect, but it would resolve the original issue!

**Comment by anaulin** [comment]
Improved in https://github.com/doubleunion/arooo/pull/522
