### ISSUE TITLE
Incorporate Travis CI into deployment processes

### ISSUE THREAD

**Issue by gitsteph** [doubleunion/arooo#301]
Linda [@compwron](https://github.com/compwron) brought up possibly incorporating CI into our deployment process so that we can merge + deploy updates more easily.  This would reduce bottlenecks, but risky if tests pass without catching dangerous bugs (e.g. something that inadvertently deletes images).  Our Heroku plan can retain 5 backups though, so seems like this is relatively safe to do.

**Comment by anaulin** [comment]
As part of https://github.com/doubleunion/arooo/issues/428 , we will gate on Travis CI going green before automatically pushing to `staging`. As I understand it, we don't automatically deploy to production, since that is gated on some light manual QA on `staging` first.

So I believe that this ticket is made obsolete by https://github.com/doubleunion/arooo/issues/428, and thus I'll close this one. (But please feel free to re-open if I'm misunderstanding something or if this needs more discussion!)
