### ISSUE TITLE
Hey, I would love to use this for a women-led co-working space

### ISSUE THREAD

**Issue by angusmcleod** [doubleunion/arooo#307]
Hey, this looks like a great project 👏

I am a cisgender man, but I work out of [OneRoofWomen](http://oneroofwomen.com/) in Melbourne Australia. OneRoof (OR) is a space for women-led businesses.  I don't work for OR, but I used to be the head of technology at a co-working space network called [Knotel](https://knotel.com/), so I give OR informal advice on tech every now and then. I work on [this](https://civically.io/), and build open source plugins for [Discourse](https://discourse.org/) (a big discussions project, built on rails).

OneRoof is currently looking for a way to give their members their own private online space. I would love to suggest to the OR team that they use and contribute to Arooo to make that happen. OneRoof's needs are a bit different from DU's, but there would hopefully be enough overlap for it to work. Also, an awesome open source feminist project like this would potentially make for a great project to share with other members in the space. For example [CodeLikeAGirl](https://codelikeagirl.org) works out of OneRoof. 

Now, I haven't talked with OneRoof (or CodeLikeAGirl) about this yet. I don't work or speak for them. I thought I should run it by you folks first, to see how open you are currently to collaborating, accepting PRs for new features and making some existing functionality optional.

Specifically OR wants to let members:
1. See who the other members are
   - Arooo does this, which is great. Would you be open to accepting PRs for improving the UX?

2. See a list of the experts (basically a better, private, version of this:  http://oneroofwomen.com/our-experts/); and
   - This would be a new page, with a list of members who are experts.

3. See a list of member discounts and deals with other businesses.
   - This would be a new page with a list of deals / businesses.

For existing functionality, we would need to

1. Have a way of disabling the voting functionality on a site-specific basis. OR is social enterprise, but it's a more traditional business and not administered democratically. Members pay monthly fees and most people (as long as they're a women-led business, or closely and clearly ascribe to OR's values (which is why I'm there)) are accepted if they want to join.

2. Have a way of changing the list of user states (related to 1).

3. Have a way of disabling the "Dues" functionality. OR already has a payment process set up (Xero), and I'm not sure they'd be interested in changing that.

Now that I've written this all out, it does seem like quite a few changes! 🙂

Well, I guess I'll run this by you anyway, as it does _feel_ like there's an opportunity for collaboration here, even if the specifics seem a bit daunting.

**Comment by brittag** [comment]
Hi, thanks for checking out the code and asking about it! That sounds interesting and fun. Because your space has some different needs and goals, I would suggest forking the codebase and trying out your own changes in that version, without having to be concerned about whether they're in sync with DU's needs.

I'd encourage you to send back any improvements DU might benefit from as PRs - we'd especially be interested in security improvements and UX improvements. I bet we could find something fun to do with an "experts" feature, and we could also think of something to do with a business feature, such as internally listing businesses owned by members.

I'd also suggest checking out the [Nadine Project](http://nadineproject.org/) if you haven't run into it yet (https://github.com/nadineproject/nadine). It's a completely different project for managing a coworking space, with some overlap in features with Arooo.

**Comment by angusmcleod** [comment]
Thanks for the quick response @brittag 👍 Yes, I think that's a good strategy. I'll play around with Arooo to see if I can make it work for OneRoof. Thanks also for the tip about Nadine!

**Comment by brittag** [comment]
Cool, feel free to open a new issue if you have any questions about the code or anything!
