### ISSUE TITLE
Applicant sees error on (successful) app submission

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#317]
We received a bug report via email to join@
This is probably an issue with something in `models/application.rb` in the section `state_machine :state, initial: :started do` 
Going by timestamp, this application was successfully submitted *before* the bug report was submitted. 
> I tried to apply for membership and the form spits out a message "Application not submitted: State cannot transition via "submit"

**Comment by compwron** [comment]
It happened again. I checked the logs using `heroku logs --tail --remote production` and didn't see any errors, and the application was submitted successfully. 
<img width="792" alt="Screen Shot 2019-05-17 at 9 22 39 PM" src="https://user-images.githubusercontent.com/578159/57964459-db64af80-78ea-11e9-9022-78dc1933ff89.png">

**Comment by anaulin** [comment]
If the user submitting their application does not have their state as "visitor" (e.g. they are a former member, or a rejected applicant), the state machine that keeps track of a user's standing will not allow this submission, because it is not possible to transition to "applicant" from that state.

If we want to allow former members and reject members to re-apply via the standard application system, we'll need to tweak the allowed state transitions. If we do this, we might want to think about a way to keep track of certain "previous states", e.g. if someone goes from former member to applicant, it would be nice to keep track in the database of the fact they used to be a member (maybe this is a new column on the `users` table that records previous states).

**Comment by anaulin** [comment]
Improved in https://github.com/doubleunion/arooo/pull/523
