### ISSUE TITLE
Give admins a way to see all enabled/disabled door codes, including non-member ones

### ISSUE THREAD

**Issue by anaulin** [doubleunion/arooo#478]
Right now, the only way admins can manage door codes through Arooo is in the "Manage members" view. This means that there is no admin visibility into door codes that are granted to "visitor" users (such as the door code for our landlord, or the door codes that we give out to package deliveries). It would be good to give admins more visibility into _all_ the door codes that exist in Arooo, and ways to administer them.

One possible solution is to create a new view, perhaps titled "Space access", which lists all doorcodes and their metadata, and gives a way to manage them. This list could have a section at the top to show "non-member" or "visitor" doorcodes that are enabled.

If we created a page for "space access", that would also be a good place to eventually add better tooling to manage the August lock access, as suggested in https://github.com/doubleunion/arooo/issues/386

**Comment by brittag** [comment]
This is outdated now because we have a new way of managing codes. The privileged codes are in our password manager (and we shared the primary one with our landlord), and the rest of the codes are in our member management app. We won't set up a code for package deliveries, because we don't have a lobby anymore.
