### ISSUE TITLE
Ask for Google-friendly email upfront during the application process

### ISSUE THREAD

**Issue by brittag** [doubleunion/arooo#487]
Right now, after a member is accepted, they need to do two things: add in their google-friendly email address and set up their dues or a scholarship. This is a hassle for membership coordinators because they need to remind people to set up their Google-friendly email, sometimes even after the person has set up their dues.

This means we should ask for Google-friendly email upfront during the application process instead of after they apply, so that the post-application process is simplified:

1. People add their dues or apply for a scholarship
2. The membership coordinator uses the existing Google-friendly email on file to set up the person's access to things

**Comment by brittag** [comment]
This should also resolve most of the issue at https://github.com/doubleunion/arooo/issues/339

**Comment by brittag** [comment]
Also, if an applicant logs in using Google authentication, we already know a good Google-friendly email address for them! We should auto-fill their "Google-friendly email" with their Google account info. They can review and update it while filling out their application.

For people with GitHub accounts, I figure this shouldn't be a required field, in case somebody _really_ wants to join without a Google address.

**Comment by brittag** [comment]
If/when we do this, we'll need to update the text of these automated email reminders again: https://github.com/doubleunion/arooo/pull/527

**Comment by brittag** [comment]
Example copy for the membership application (might not fit well - just an example of the idea):

Contact email: [ ] 
Google account email (if different from contact email): [ ] We use Google Drive and Google Calendar for internal coordination for members, so this helps us add you to these resources if you get accepted as a member.

**Comment by sarahwalters** [comment]
Is it alright if I work on this issue? Started experimenting and I think I see how to make this change. I think I'm not able to assign the issue to myself since I'm not a collaborator in the repo.

I also noticed some minor inconsistencies on the application edit and show pages (e.g. on the edit page "required" is not in parentheses but "optional" is; e.g. not all fields on the show page are marked as "required" or "optional"). Is it okay to attach two PRs to this issue, one PR to clean up those minor inconsistencies and another PR to add the feature -- or would it be better to create a separate issue for the cleanups?

**Comment by anaulin** [comment]
@sarahwalters yes, please and thank you! I have assigned this issue to you.

It is fine to attach multiple PRs to this issue, or just do small clean-up PRs without a specific issue. (Our current PR load is so small that we can afford not to be picky about keeping things extra-tidy.)

I also sent you an invitation to join the DU org so that you can have some basic write permissions in this repo.
