### ISSUE TITLE
Add issue template?

### ISSUE THREAD

**Issue by compwron** [doubleunion/arooo#543]

**Comment by carlyrobison** [comment]
I saw some prompts when I opened new issues. For a feature request:

**What type of user is this for? (applicant/member/voting member/admin)**

**Description**

**Screenshots of current behavior, if any**

**Comment by brittag** [comment]
Yes! I think the existing issue templates (https://github.com/doubleunion/arooo/tree/main/.github/ISSUE_TEMPLATE) are fine. I might call a "feature request" an "idea" in the context of DU (since we're more informal and concept-oriented than a traditional software project), but it doesn't matter much.
