### ISSUE TITLE
Store who has keys, keycodes in the app

### ISSUE THREAD

**Issue by lilliealbert** [doubleunion/arooo#97]
We should possibly remove a spreadsheet from the world by creating a page to track who has keys and keycodes.

Question: should the keycodes themselves be stored in the app? Burying them somewhere in a private Google doc seems more secure to me, since the app getting hacked would mean people had literal access to the space. 

Paging @dharlette for your input as key keeper!

**Comment by brittag** [comment]
We currently have our authoritative list of keycodes maintained separately (as part of a Twilio app), and this doesn't really cause problems for me as a membership coordinator. (We already have a number of other separate systems that the membership coordinator needs to keep in sync!)

So I'm fine with having this separate rather than trying to integrate the two systems - I'll close this.
